name: Proftpd
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: jms1989/proftpd
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
